###################################
#     Minecraft Jinro Config
#        Author: axtuki1
###################################

# メッセージの前に表示されるラベル的なやつ
Prefix: "§a[§bMinecraftJinro§a]"

# スポーンポイントの座標
spawnpoint:
  x:
  y:
  z:

# 霊界(死亡後にテレポートされる場所)の座標
reikai:
  x:
  y:
  z:

#　諸情報のスコアボードの内部の名前
InfoObjectiveName: "MinecraftJinro"

# チャットカウンターを使用するか
ChatCounterEnable: true

# チャットカウンターのスコアボードの内部の名前
ChatCounterObjectiveName: "ChatCounter"

# プレイヤーリストとチャットにCOした役職を表示するか
ShowComingOut: true

# COを含む発言があった場合にサウンド通知を行うか
NoticeComingOut: true

# 勝利判定をタイトルで表示するか
WinnerMsgUseTitle: false

# 占い師/霊能者の結果を役職で表示するか
ShowYakusyoku: true

# 人形使いが人形を使用にした時に通知を出すか
ShowUseNingyou: false

# 参加者以外のログイン時に観戦モードにするか
LoginSpectatorMode: true

# 夜の時間(秒数)
NightTime: 180

# 昼(議論中)の時間(秒数)
DiscussionTime: 300

# MySQLの設定
sql:
  enable: true
  url: jdbc:mysql://localhost/MinecraftJinro
  user: "Minecraft"
  password: "Minecraft"


# ログイン時のメッセージ
LoginAttention:
  enable: false
  title: "重要"
  msg: "人狼サーバーです(*´ω｀*)"

###################################
#  DEBUG
###################################
# プラグインロード時のStatusとCycleの設定。
Debug: false
BootStatus: Standby
BootCycle: Standby
